//import "./pages/global/index.cy"
//import "./pages/global/scenes.cy"
//import "./pages/global/users.cy"
//import "./pages/global/parcels.cy"
//import "./pages/global/map.cy"
//import "./pages/local/topbar.cy"
